In [1]:
# Import required libraries
import pandas as pd

In [3]:
# Load the trp island report data
df = pd.read_csv("trp_island_gbks/trp_island_report.tsv", sep="\t")
df.head()

,source_file,record_id,start,end,span_bp,trpE_label,trpG_label,region_file
0,Pseudomonas_syringae_pv_syringae_2340_3879.gbk...,NZ_LIHT01000078.1,13562,39901,24340,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_pv_syringae_2340_3879_NZ...
1,Pseudomonas_syringae_BS2900_5075.gbk ...,NZ_FNPP01000004.1,342240,366589,22350,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_BS2900_5075_NZ_FNPP01000...
2,Pseudomonas_syringae_BS3829_5514.gbk ...,NZ_FOPR01000011.1,13464,37089,21626,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_BS3829_5514_NZ_FOPR01000...
3,Pseudomonas_syringae_SHV323_17590.gbk ...,NZ_JAHARZ010000001.1,2677751,2701087,21337,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_SHV323_17590_NZ_JAHARZ01...
4,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...,NZ_JH951894.1,13319,44154,28836,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_pv_avellanae_ISPaVe037_2...

In [4]:
# Clean up column names and sort by distance
df.columns = df.columns.str.strip()
df.sort_values(by=["span_bp"], ascending=False)

,source_file,record_id,start,end,span_bp,trpE_label,trpG_label,region_file
93,Pseudomonas_syringae_isolate_CFBP3846_6577.gbk...,NZ_LT963402.1,5487032,5672426,183395,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_isolate_CFBP3846_6577_NZ...
35,Pseudomonas_syringae_UB303_12214.gbk ...,NZ_CP047267.1,5344978,5416547,69570,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_UB303_12214_NZ_CP047267....
92,Pseudomonas_syringae_Susan2139_17596.gbk ...,NZ_CP074578.1,5022065,5061474,37410,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_Susan2139_17596_NZ_CP074...
4,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...,NZ_JH951894.1,13319,44154,28836,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_pv_avellanae_ISPaVe037_2...
58,Pseudomonas_syringae_pv_tomato_delta_X_12208.g...,NZ_CP047073.1,622639,652982,28344,trpE,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_pv_tomato_delta_X_12208_...
...,...,...,...,...,...,...,...,...
9,Pseudomonas_syringae_pv_actinidiae_P155_11457....,NZ_CP032870.1,12181,16237,2057,anthranilate synthase component I family protein,anthranilate synthase component II ...,Pseudomonas_syringae_pv_actinidiae_P155_11457...
61,Pseudomonas_syringae_CRAFRU_1408_5396.gbk ...,NZ_CP019733.1,17680,21736,2057,anthranilate synthase component I family protein,anthranilate synthase component II ...,Pseudomonas_syringae_CRAFRU_1408_5396_NZ_CP01...
123,Pseudomonas_syringae_pv_actinidiae_str_Shaanxi...,NZ_CP032632.1,29595,33651,2057,anthranilate synthase component I family protein,anthranilate synthase component II ...,Pseudomonas_syringae_pv_actinidiae_str_Shaanx...
77,Pseudomonas_syringae_NZ45_6142.gbk ...,NZ_MTZF01000002.1,27073,31129,2057,anthranilate synthase component I family protein,anthranilate synthase component II ...,Pseudomonas_syringae_NZ45_6142_NZ_MTZF0100000...
6,Pseudomonas_syringae_pv_maculicola_MAFF_302723...,NZ_CP067024.1,229596,233205,1610,anthranilate synthase component I family protein,aminodeoxychorismate/anthranilate synthase co...,Pseudomonas_syringae_pv_maculicola_MAFF_30272...

In [5]:
# Remove leading/trailing whitespace from all string columns
str_cols = df.select_dtypes(include=['object']).columns
df[str_cols] = df[str_cols].apply(lambda x: x.str.strip())

In [6]:
# Check value counts for trpG_label
df.trpG_label.value_counts()

trpG_label
aminodeoxychorismate/anthranilate synthase component II    143
anthranilate synthase component II                          20
Name: count, dtype: int64

In [8]:
# Remove unwanted trpG_label entries
df = df[(df["trpG_label"] != "pyocyanine specific anthranilate synthase component II") & (df["trpG_label"] != "phnB")]
df.trpG_label.value_counts()

trpG_label
aminodeoxychorismate/anthranilate synthase component II    143
anthranilate synthase component II                          20
Name: count, dtype: int64

In [9]:
# Check value counts for trpE_label
df.trpE_label.value_counts()

trpE_label
trpE                                                141
anthranilate synthase component I family protein     22
Name: count, dtype: int64

In [10]:
# Remove unwanted trpG_label entries
df = df[(df["trpE_label"] == "trpE")]
df.trpE_label.value_counts()

trpE_label
trpE    141
Name: count, dtype: int64

In [13]:
df.columns

Index(['source_file', 'record_id', 'start', 'end', 'span_bp', 'trpE_label',
       'trpG_label', 'region_file'],
      dtype='object')

In [ ]:
# Sort by distance and remove first 3 rows
df.sort_values(by=["span_bp"], ascending=False, inplace=True)
#df = df.iloc[3:, :]

In [15]:
# Preview the DataFrame
df.head()

,source_file,record_id,start,end,span_bp,trpE_label,trpG_label,region_file
93,Pseudomonas_syringae_isolate_CFBP3846_6577.gbk,NZ_LT963402.1,5487032,5672426,183395,trpE,aminodeoxychorismate/anthranilate synthase com...,Pseudomonas_syringae_isolate_CFBP3846_6577_NZ_...
35,Pseudomonas_syringae_UB303_12214.gbk,NZ_CP047267.1,5344978,5416547,69570,trpE,aminodeoxychorismate/anthranilate synthase com...,Pseudomonas_syringae_UB303_12214_NZ_CP047267.1...
92,Pseudomonas_syringae_Susan2139_17596.gbk,NZ_CP074578.1,5022065,5061474,37410,trpE,aminodeoxychorismate/anthranilate synthase com...,Pseudomonas_syringae_Susan2139_17596_NZ_CP0745...
4,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...,NZ_JH951894.1,13319,44154,28836,trpE,aminodeoxychorismate/anthranilate synthase com...,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...
58,Pseudomonas_syringae_pv_tomato_delta_X_12208.gbk,NZ_CP047073.1,622639,652982,28344,trpE,aminodeoxychorismate/anthranilate synthase com...,Pseudomonas_syringae_pv_tomato_delta_X_12208_N...

In [17]:
# Search .gbk files for keywords and map to DataFrame
import os
from collections import defaultdict
gbk_dir = "trp_island_gbks"
keywords = ["phage", "capsid", "tail fiber", "baseplate"]
gbk_files = [f for f in os.listdir(gbk_dir) if f.endswith('.gbk')]
file_keyword_map = defaultdict(list)
for gbk_file in gbk_files:
    with open(os.path.join(gbk_dir, gbk_file), 'r') as f:
        content = f.read().lower()
        for kw in keywords:
            if kw in content:
                file_keyword_map[gbk_file].append(kw)
def find_matching_gbk(source_file):
    if not isinstance(source_file, str):
        return None
    prefix = source_file.replace('.gbk', '')
    for gbk_file in gbk_files:
        if gbk_file.startswith(prefix):
            return gbk_file
    return None
df['matched_gbk_file'] = df['source_file'].apply(find_matching_gbk)
def get_keywords_for_matched_file(row):
    fname = row['matched_gbk_file']
    if fname in file_keyword_map:
        return ', '.join(file_keyword_map[fname])
    return ''
df['gbk_keywords'] = df.apply(get_keywords_for_matched_file, axis=1)
df[['source_file', 'matched_gbk_file', 'gbk_keywords']].head()

,source_file,matched_gbk_file,gbk_keywords
93,Pseudomonas_syringae_isolate_CFBP3846_6577.gbk,Pseudomonas_syringae_isolate_CFBP3846_6577_NZ_...,phage
35,Pseudomonas_syringae_UB303_12214.gbk,Pseudomonas_syringae_UB303_12214_NZ_CP047267.1...,"phage, capsid, tail fiber, baseplate"
92,Pseudomonas_syringae_Susan2139_17596.gbk,Pseudomonas_syringae_Susan2139_17596_NZ_CP0745...,"phage, baseplate"
4,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...,Pseudomonas_syringae_pv_avellanae_ISPaVe037_29...,"phage, baseplate"
58,Pseudomonas_syringae_pv_tomato_delta_X_12208.gbk,Pseudomonas_syringae_pv_tomato_delta_X_12208_N...,phage

In [20]:
df.gbk_keywords.value_counts()

gbk_keywords
phage, tail fiber, baseplate            71
phage, baseplate                        55
                                        11
phage                                    3
phage, capsid, tail fiber, baseplate     1
Name: count, dtype: int64

In [21]:
# Show summary statistics for distance_bp
df.span_bp.describe()

count       141.000000
mean      24216.404255
std       14723.898405
min        4457.000000
25%       22146.000000
50%       23553.000000
75%       24838.000000
max      183395.000000
Name: span_bp, dtype: float64

In [23]:
# Filter rows with distance_bp >= 10000
df = df[df["span_bp"] >= 10000]
df.shape

(135, 10)

In [24]:
# Save the cleaned DataFrame to a TSV file
df.to_csv("cleaned_trp_island_report.tsv", sep="\t", index=False)

In [25]:
# Remove .gbk files not present in matched_gbk_file column
keep_files = set(df['matched_gbk_file'].dropna())
all_gbk_files = [f for f in os.listdir(gbk_dir) if f.endswith('.gbk')]
for gbk_file in all_gbk_files:
    if gbk_file not in keep_files:
        os.remove(os.path.join(gbk_dir, gbk_file))
        print(f"Removed: {gbk_file}")
print(f"Kept {len(keep_files)} .gbk files. Removed {len(all_gbk_files) - len(keep_files)} files.")

Removed: Pseudomonas_syringae_CFBP8777_17546_NZ_JACYWS010000010.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_tomato_DAPP-PG_215_isolate_IPVPG_215_26092_NZ_OX458335.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_PDD-32b-74_7155_NZ_MTSA01000027.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_CFBP13574_17542_NZ_JACYWI010000012.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_actinidiae_ICMP_9617_2475_NZ_CM002753.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_isolate_inb918_11494_NZ_CP024646.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_MAFF212063_6757_NZ_CP024712.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_actinidiae_PSAAH01_20743_NZ_CP116479.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_antirrhini_str_126_26093_NZ_CP126992.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_actinidiae_P155_11457_NZ_CP032871.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_CRAFRU_1408_5396_NZ_CP019732.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_B13-200_7111_NZ_CP019871.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_BS3827_5522_NZ_FOQB01000002.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_MB03_4121_NZ_LAGV01000003.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_maculicola_MAFF_302723_17520_NZ_CP067024.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_PA-6-8C_17604_NZ_WKEQ01000010.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_actinidiae_str_Shaanxi_M228_11439_NZ_CP032632.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_9643_6237_NZ_MLET01000007.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_ICMP_9853_5177_NZ_CP018202.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_ICMP_11292_3810_NZ_LKGU01000070.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_actinidiae_MAFF613020_17763_NZ_AP019411.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_CFBP_3800_5881_NZ_OLMQ01000001.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_tomato_BRIP38746_11422_NZ_SNVG01000009.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_pv_maculicola_M4a_3822_NZ_LGLE01000026.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_CFBP13571_17544_NZ_JACYWJ010000010.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_isolate_CFBP6411_6140_NZ_LT963408.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_GAW0119_2477_NZ_JPQU01000058.1_trpE_trpG.gbk
Removed: Pseudomonas_syringae_NZ45_6142_NZ_MTZF01000002.1_trpE_trpG.gbk
Kept 135 .gbk files. Removed 28 files.